"""review warnings on agent runs

Revision ID: b04f052d3d3e
Revises: ebbd9d7dc41b
Create Date: 2026-10-01 17:23:44.888247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b04f052d3d3e'
down_revision: Union[str, Sequence[str], None] = 'ebbd9d7dc41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('review_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'review_warnings')
    # ### end Alembic commands ###
