"""agent run plan usage and cancel

Revision ID: b88d25944321
Revises: deb3d64694ad
Create Date: 2026-10-01 10:38:46.354646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88d25944321'
down_revision: Union[str, Sequence[str], None] = 'deb3d64694ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('plan', sa.Text(), nullable=True))
    op.add_column('agent_runs', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('agent_runs', sa.Column('llm_calls', sa.Integer(), server_default='0', nullable=False))
    op.add_column('agent_runs', sa.Column('prompt_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('agent_runs', sa.Column('completion_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('agent_runs', sa.Column('cancel_requested', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'cancel_requested')
    op.drop_column('agent_runs', 'completion_tokens')
    op.drop_column('agent_runs', 'prompt_tokens')
    op.drop_column('agent_runs', 'llm_calls')
    op.drop_column('agent_runs', 'attempts')
    op.drop_column('agent_runs', 'plan')
    # ### end Alembic commands ###
