"""lazy embeddings for large repo indexes

Revision ID: bcc6ef434d5e
Revises: a73661dacbb6
Create Date: 2026-10-01 16:43:07.561332

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc6ef434d5e'
down_revision: Union[str, Sequence[str], None] = 'a73661dacbb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repo_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=True)
    op.add_column('repo_indexes', sa.Column('fully_embedded', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Lazily-embedded indexes can't satisfy NOT NULL; they are caches, drop them.
    op.execute("DELETE FROM repo_indexes WHERE NOT fully_embedded")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_indexes', 'fully_embedded')
    op.alter_column('repo_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=False)
    # ### end Alembic commands ###
