"""repository rag index and run retrieval

Revision ID: cb5554ccaecd
Revises: b88d25944321
Create Date: 2026-10-01 11:56:49.539056

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb5554ccaecd'
down_revision: Union[str, Sequence[str], None] = 'b88d25944321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must be installed on the server (see infra/postgres/Dockerfile).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_indexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('embedding_model', sa.String(length=200), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_url', 'commit_sha', 'embedding_model')
    )
    op.create_table('repo_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', path || ' ' || content)", persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['repo_indexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_chunks_index_id'), 'repo_chunks', ['index_id'], unique=False)
    op.create_index('ix_repo_chunks_tsv', 'repo_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.add_column('agent_runs', sa.Column('use_rag', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('agent_runs', sa.Column('target_path', sa.String(length=500), nullable=True))
    op.add_column('agent_runs', sa.Column('retrieval', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('tasks', 'target_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Tasks created without a target file can't satisfy NOT NULL again; mark them.
    op.execute("UPDATE tasks SET target_path = '' WHERE target_path IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'target_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('agent_runs', 'retrieval')
    op.drop_column('agent_runs', 'target_path')
    op.drop_column('agent_runs', 'use_rag')
    op.drop_index('ix_repo_chunks_tsv', table_name='repo_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_repo_chunks_index_id'), table_name='repo_chunks')
    op.drop_table('repo_chunks')
    op.drop_table('repo_indexes')
    # ### end Alembic commands ###
