"""optional test command

Revision ID: cd0da6a97ae8
Revises: cb5554ccaecd
Create Date: 2026-10-01 15:29:16.467449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd0da6a97ae8'
down_revision: Union[str, Sequence[str], None] = 'cb5554ccaecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'test_command',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("UPDATE tasks SET test_command = '' WHERE test_command IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'test_command',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###
