"""github binding for tasks runs approvals

Revision ID: deb3d64694ad
Revises: b698e033df6b
Create Date: 2026-09-30 21:54:27.219531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb3d64694ad'
down_revision: Union[str, Sequence[str], None] = 'b698e033df6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('base_commit', sa.String(length=64), nullable=True))
    op.add_column('approvals', sa.Column('diff_sha256', sa.String(length=64), nullable=True))
    op.add_column('approvals', sa.Column('base_commit', sa.String(length=64), nullable=True))
    op.add_column('tasks', sa.Column('repo_full_name', sa.String(length=200), nullable=True))
    op.add_column('tasks', sa.Column('base_branch', sa.String(length=200), nullable=True))
    op.add_column('tasks', sa.Column('issue_number', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('issue_title', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('issue_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'issue_url')
    op.drop_column('tasks', 'issue_title')
    op.drop_column('tasks', 'issue_number')
    op.drop_column('tasks', 'base_branch')
    op.drop_column('tasks', 'repo_full_name')
    op.drop_column('approvals', 'base_commit')
    op.drop_column('approvals', 'diff_sha256')
    op.drop_column('agent_runs', 'base_commit')
    # ### end Alembic commands ###
